/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wentware.test.djikstra;

import java.util.Arrays;
import java.util.Scanner;

import static java.lang.System.out;

public class App {

    public static void main(String[] args) {
        App app = new App();
        int response = app.run(args);
        System.exit(response);
    }

    private int run(String[] args)  {
        out.println("Starting Graph");
        try {
            String sourceVertName = args[0];
            String destVertName = args[1];
            String[] remainingArgs = Arrays.copyOfRange(args, 2, args.length);
            Graph graph = parse(remainingArgs);
            DijkstraAlgo algo = new DijkstraAlgo(graph, sourceVertName, destVertName);
            DijkstraAlgo.Solution solution = algo.traverse();
            out.println("Cost was " + solution.cost());
            out.println("Path was " + solution.path());
            return 0;
        } catch (Exception e) {
            System.err.println(e.getMessage());
            return -1;
        }
    }

    public Graph parse(String[] args) throws Exception {
        try (Scanner scanner = new Scanner(String.join("\n", args))) {
            Graph graph = new Graph();

            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] parts = line.split(",");


                if (parts.length == 3) {

                    Vert from = graph.addVert(parts[0]);
                    Vert to = graph.addVert(parts[1]);
                    int weight = Integer.parseInt(parts[2]);
                    from.addEdgeTo(to, weight);
                    //assume edge, add any new verts
                } else {
                    String message = String.format("could not parse line %s", line);
                    throw new Exception(message);
                }
            }
            return graph;
        }
    }
}
