/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wentware.test.djikstra;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static java.lang.System.out;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {

    private App classUnderTest;

    @BeforeEach
    void setUp() {
        classUnderTest = new App();
    }

    @Test
    void parse_withGoodData() throws Exception {
        String[] args = Fixture.GRAPH_DEF;

        Graph g = classUnderTest.parse(args);
        assertNotNull(g);
        assertEquals(4, g.getNodes().size());
        Graph.Node n1 = g.findNodeById("N1").orElseThrow();
        assertEquals(2, n1.getEdges().size());
        Graph.Node n2 = g.findNodeById("N2").orElseThrow();
        assertEquals(2, n2.getEdges().size());
        Graph.Node n3 = g.findNodeById("N3").orElseThrow();
        assertEquals(1, n3.getEdges().size());
        assertNotNull(n3.getEdges().stream().filter(e -> "N4".equals(e.getToNode().getId())).findFirst());
    }

    @Test
    void run_withGoodGraph() throws Exception {
        String[] args = new String[6];
        args[0] = "N1";
        args[1] = "N2";
        for(int i=2;i < 6;i++) {
            args[i] = Fixture.GRAPH_DEF[i-2];
        }
        int res = classUnderTest.run(args);
        assertEquals(0, res);
    }
}
